export type Priority = 'Hot' | 'Warm' | 'Cold'

export interface ScoreBreakdown {
  industryFit: number      // 0-25
  companySize: number      // 0-25
  digitalMaturity: number  // 0-25
  securityNeeds: number    // 0-25
}

export interface Contact {
  name: string
  title: string
  email: string
  linkedin?: string
}

export interface Lead {
  id: string
  company: string
  website: string
  industry: string
  size: string
  country: string
  city: string
  employees: string
  description: string
  score: number
  scoreBreakdown: ScoreBreakdown
  whyGoodFit: string
  suggestedSolution: string
  contactApproach: string
  priority: Priority
  scrapedAt: string
  linkedinUrl?: string
  contacts?: Contact[]
}

// ── 30 Pre-seeded CDMX leads ──────────────────────────────────────────────────
export const seedLeads: Lead[] = [
  // ── HOT ──────────────────────────────────────────────────────────────────
  {
    id: 'S001',
    company: 'BBVA México',
    website: 'https://www.bbva.mx',
    industry: 'Banca y Finanzas',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '40,000+',
    description: 'Segundo banco más grande de México con más de 22 millones de clientes digitales y fuerte estrategia de banca móvil y open banking.',
    score: 95,
    scoreBreakdown: { industryFit: 25, companySize: 25, digitalMaturity: 23, securityNeeds: 22 },
    whyGoodFit: 'Alta base de usuarios digitales requiere CIAM robusto. Regulaciones CNBV exigen controles de identidad estrictos. Activa adopción de open banking amplifica necesidades de seguridad de API.',
    suggestedSolution: 'Auth0 (CIAM), Okta (IAM Workforce), CrowdStrike (endpoint)',
    contactApproach: 'Presentar caso de éxito de banco similar con Auth0. Destacar cumplimiento CNBV/PCI-DSS y reducción de fraude en onboarding digital.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/bbva-mexico',
    contacts: [
      { name: 'Rafael Hernández Santos', title: 'CISO', email: 'r.hernandez@bbva.mx', linkedin: 'https://www.linkedin.com/in/rafael-hernandez-bbva' },
      { name: 'Ignacio Martínez García', title: 'CTO', email: 'i.martinez@bbva.mx' },
      { name: 'Ana González Pérez', title: 'Directora de Identidad Digital', email: 'a.gonzalez@bbva.mx' },
    ],
  },
  {
    id: 'S002',
    company: 'Citibanamex',
    website: 'https://www.banamex.com',
    industry: 'Banca y Finanzas',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '35,000+',
    description: 'Uno de los bancos con mayor presencia en México. En proceso de escisión de Citi para operar independientemente, implicando reestructura tecnológica masiva.',
    score: 92,
    scoreBreakdown: { industryFit: 25, companySize: 25, digitalMaturity: 21, securityNeeds: 21 },
    whyGoodFit: 'La separación de Citi implica re-implementar toda la infraestructura de identidad. Ventana de oportunidad enorme para establecer nueva plataforma IAM desde cero con Okta/Auth0.',
    suggestedSolution: 'Okta (IAM completo), Auth0 (banca digital), CrowdStrike Zero Trust',
    contactApproach: 'Posicionarse como socio para la transición tecnológica post-separación. Presentar roadmap de migración de identidad con mínima fricción operacional.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/citibanamex',
    contacts: [
      { name: 'Carlos Domínguez López', title: 'CISO', email: 'carlos.dominguez@banamex.com' },
      { name: 'Patricia Ramírez Torres', title: 'CTO', email: 'p.ramirez@banamex.com' },
      { name: 'José Morales Rivera', title: 'Director de Transformación Digital', email: 'j.morales@banamex.com' },
    ],
  },
  {
    id: 'S003',
    company: 'Nu México (Nubank)',
    website: 'https://nu.com.mx',
    industry: 'Fintech / Neobank',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '3,000+',
    description: 'Brazo mexicano del mayor neobank de LATAM. Millones de clientes completamente digitales con tarjeta sin anualidad y cuenta de ahorro. Crecimiento acelerado en CDMX.',
    score: 93,
    scoreBreakdown: { industryFit: 25, companySize: 22, digitalMaturity: 25, securityNeeds: 21 },
    whyGoodFit: 'Plataforma 100% digital con crecimiento explosivo requiere CIAM escalable. KYC/AML regulatorio obligatorio (CNBV). Biometría y verificación de identidad son core del onboarding.',
    suggestedSolution: 'Auth0 (CIAM nativo digital), Incode (biométrica KYC), CrowdStrike',
    contactApproach: 'Destacar integración nativa de Incode + Auth0 para onboarding en menos de 5 minutos. Cumplimiento CNBV y LFPIORPI como diferenciador ante reguladores.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/nubank',
    contacts: [
      { name: 'Diego Fernández Castro', title: 'CTO México', email: 'diego.fernandez@nu.com.mx' },
      { name: 'Valeria López Mendoza', title: 'Head of Security', email: 'valeria.lopez@nu.com.mx' },
    ],
  },
  {
    id: 'S004',
    company: 'Bitso',
    website: 'https://bitso.com',
    industry: 'Fintech / Crypto',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '1,500+',
    description: 'Exchange de criptomonedas más grande de LATAM con millones de usuarios en México, Argentina y Brasil. Opera como IFPE bajo regulación CNBV.',
    score: 91,
    scoreBreakdown: { industryFit: 24, companySize: 21, digitalMaturity: 24, securityNeeds: 22 },
    whyGoodFit: 'Activos digitales de alto valor requieren seguridad de identidad extrema. KYC/AML obligatorio bajo CNBV. Autenticación fuerte (MFA/Yubico) es crítica para proteger wallets.',
    suggestedSolution: 'Yubico (MFA físico), Auth0 (CIAM), Jumio (KYC), CrowdStrike',
    contactApproach: 'Presentar caso de reducción de fraude en plataformas crypto con Yubico + Auth0. Destacar compliance CNBV para IFPE y prevención de lavado de activos digitales.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/bitso',
    contacts: [
      { name: 'Alejandro Ruiz Vargas', title: 'CTO', email: 'a.ruiz@bitso.com' },
      { name: 'Mariana Sánchez Reyes', title: 'CISO', email: 'm.sanchez@bitso.com' },
      { name: 'Fernando Torres Vega', title: 'Director de Compliance', email: 'f.torres@bitso.com' },
    ],
  },
  {
    id: 'S005',
    company: 'Kavak',
    website: 'https://www.kavak.com',
    industry: 'Tecnología / Autotech',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '5,000+',
    description: 'Unicornio mexicano de compraventa de autos usados valuado en $8.7B USD. Operaciones en 10 países con plataforma 100% digital e identidad verificada en transacciones.',
    score: 91,
    scoreBreakdown: { industryFit: 24, companySize: 22, digitalMaturity: 24, securityNeeds: 21 },
    whyGoodFit: 'Escala masiva de usuarios con transacciones de alto valor requiere verificación de identidad robusta. Operaciones multi-país crean complejidad de IAM. Incode/Jumio encajan perfectamente.',
    suggestedSolution: 'Incode (verificación identidad), Auth0 (CIAM multi-tenant), Jumio',
    contactApproach: 'Destacar reducción de fraude en financiamientos y agilidad en KYC digital. Presentar integración Incode + Auth0 para onboarding sin fricciones.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/kavak',
    contacts: [
      { name: 'Federico Treviño García', title: 'CTO', email: 'f.trevino@kavak.com' },
      { name: 'Laura Jiménez Ortega', title: 'Directora de Ciberseguridad', email: 'l.jimenez@kavak.com' },
    ],
  },
  {
    id: 'S006',
    company: 'Clip',
    website: 'https://clip.mx',
    industry: 'Fintech / Pagos',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '2,000+',
    description: 'Líder en pagos con tarjeta para PYMEs en México. Ahora parte de OXXO/FEMSA con millones de comerciantes registrados en su plataforma de pagos.',
    score: 88,
    scoreBreakdown: { industryFit: 24, companySize: 20, digitalMaturity: 23, securityNeeds: 21 },
    whyGoodFit: 'Millones de comerciantes necesitan identidad segura. Integración FEMSA amplía base de usuarios. KYC requerido para cumplimiento CNBV y anti-lavado de dinero.',
    suggestedSolution: 'Auth0 (CIAM comerciantes), Jumio (KYC/AML), Okta Workforce',
    contactApproach: 'Presentar solución de onboarding KYC acelerado para nuevos comerciantes y cumplimiento PCI-DSS para procesamiento de pagos.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/clip',
    contacts: [
      { name: 'Rodrigo Medina Flores', title: 'CTO', email: 'r.medina@clip.mx' },
      { name: 'Sandra Torres Vega', title: 'Head of Security', email: 's.torres@clip.mx' },
    ],
  },
  {
    id: 'S007',
    company: 'Aeromexico',
    website: 'https://www.aeromexico.com',
    industry: 'Aerolíneas',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '16,000+',
    description: 'Aerolínea flag carrier de México, reestructurada tras el Capítulo 11. Fuerte inversión en transformación digital y experiencia digital del pasajero.',
    score: 85,
    scoreBreakdown: { industryFit: 20, companySize: 23, digitalMaturity: 22, securityNeeds: 20 },
    whyGoodFit: 'Millones de pasajeros en portal digital y app requieren CIAM de alto rendimiento. Sistema de lealtad Club Premier necesita identidad federada. Empleados remotos necesitan Zero Trust.',
    suggestedSolution: 'Auth0 (CIAM pasajeros), Okta (workforce), Zscaler (Zero Trust)',
    contactApproach: 'Mostrar reducción de fricción en login de la app y aumento de conversión. Mencionar cumplimiento IATA/TSA para seguridad de empleados.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/aeromexico',
    contacts: [
      { name: 'Miguel Ángel Reyes Cruz', title: 'CIO', email: 'm.reyes@aeromexico.com' },
      { name: 'Gabriela Herrera Morales', title: 'Directora de Ciberseguridad', email: 'g.herrera@aeromexico.com' },
      { name: 'Luis Pérez Sandoval', title: 'Director de Transformación Digital', email: 'l.perez@aeromexico.com' },
    ],
  },
  {
    id: 'S008',
    company: 'Santander México',
    website: 'https://www.santander.com.mx',
    industry: 'Banca y Finanzas',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '20,000+',
    description: 'Tercer banco por activos en México, parte de Grupo Santander global. Inversión en banca digital con Openbank como plataforma digital independiente.',
    score: 86,
    scoreBreakdown: { industryFit: 25, companySize: 23, digitalMaturity: 20, securityNeeds: 18 },
    whyGoodFit: 'Apertura de Openbank en México crea necesidad de CIAM nativo digital. Regulación CNBV. Migración a la nube requiere Zero Trust y IAM moderno.',
    suggestedSolution: 'Auth0 (Openbank CIAM), Okta Workforce, CrowdStrike',
    contactApproach: 'Presentar propuesta para el lanzamiento de Openbank México con Auth0. Caso de éxito de Santander España con plataforma de identidad centralizada.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/santander-mexico',
    contacts: [
      { name: 'Antonio Vargas Molina', title: 'CISO', email: 'a.vargas@santander.com.mx' },
      { name: 'Elena Morales Díaz', title: 'Directora Digital & Openbank', email: 'e.morales@santander.com.mx' },
      { name: 'Ricardo Ibáñez Torres', title: 'CIO', email: 'r.ibanez@santander.com.mx' },
    ],
  },
  {
    id: 'S009',
    company: 'Kueski',
    website: 'https://kueski.com',
    industry: 'Fintech / Crédito Digital',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '800+',
    description: 'Plataforma líder de crédito digital en México con Kueski Pay (BNPL) y Kueski Up (préstamos personales). Millones de usuarios con scoring crediticio automatizado.',
    score: 89,
    scoreBreakdown: { industryFit: 24, companySize: 18, digitalMaturity: 24, securityNeeds: 23 },
    whyGoodFit: 'Plataforma 100% digital con millones de usuarios requiere CIAM de alta disponibilidad. KYC/AML obligatorio por regulación CNBV. Prevención de fraude identitario es prioridad crítica.',
    suggestedSolution: 'Auth0 (CIAM), Incode (biométrica/KYC), Jumio (verificación documentos)',
    contactApproach: 'Presentar reducción de fraude en solicitudes de crédito usando biometría Incode + Auth0. Mencionar cumplimiento CNBV y aceleración de onboarding.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/kueski',
    contacts: [
      { name: 'Andrés Castillo Núñez', title: 'CTO', email: 'a.castillo@kueski.com' },
      { name: 'Isabel Flores García', title: 'Head of Security Engineering', email: 'i.flores@kueski.com' },
    ],
  },
  {
    id: 'S010',
    company: 'Konfío',
    website: 'https://konfio.mx',
    industry: 'Fintech / Banca PYMEs',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '1,200+',
    description: 'Plataforma financiera para PYMEs con crédito, cuentas de negocio y pagos. Respaldada por SoftBank y Goldman Sachs. Fuerte enfoque en onboarding digital 100%.',
    score: 88,
    scoreBreakdown: { industryFit: 23, companySize: 17, digitalMaturity: 24, securityNeeds: 24 },
    whyGoodFit: 'Onboarding 100% digital de PYMEs requiere KYC robusto. Regulación CNBV exige verificación de identidad de representantes legales. Tarjeta Konfío necesita autenticación fuerte.',
    suggestedSolution: 'Incode (KYC empresarial), Auth0 (CIAM), Jumio (documentos)',
    contactApproach: 'Mostrar cómo Incode reduce el tiempo de activación de cuenta empresarial. Cumplimiento LFPIORPI para prevención de lavado de dinero.',
    priority: 'Hot',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/konfio',
    contacts: [
      { name: 'Jorge Gutiérrez Soto', title: 'CTO', email: 'j.gutierrez@konfio.mx' },
      { name: 'Diana Ramírez Torres', title: 'Head of Cybersecurity', email: 'd.ramirez@konfio.mx' },
    ],
  },

  // ── WARM ─────────────────────────────────────────────────────────────────
  {
    id: 'S011',
    company: 'Albo',
    website: 'https://albo.mx',
    industry: 'Fintech / Neobank',
    size: 'Mid-Market',
    country: 'México',
    city: 'Ciudad de México',
    employees: '400+',
    description: 'Neobank mexicano con cuenta de débito digital sin comisiones. Enfocado en la bancarización de mexicanos con app móvil y tarjeta Mastercard.',
    score: 82,
    scoreBreakdown: { industryFit: 23, companySize: 14, digitalMaturity: 24, securityNeeds: 21 },
    whyGoodFit: 'Plataforma digital pura requiere CIAM desde el primer día. Crecimiento acelerado de usuarios exige escalabilidad de identidad. Regulación CNBV para fintech.',
    suggestedSolution: 'Auth0 (CIAM neobank), Incode (KYC), Jumio',
    contactApproach: 'Enfocar en solución CIAM nativa para neobanks. Presentar casos de éxito en fintechs latinoamericanas con onboarding biométrico.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/albo',
    contacts: [
      { name: 'Pablo Mendoza Cruz', title: 'CTO', email: 'p.mendoza@albo.mx' },
      { name: 'Camila Ortega Vásquez', title: 'Head of Security', email: 'c.ortega@albo.mx' },
    ],
  },
  {
    id: 'S012',
    company: 'Rappi México',
    website: 'https://www.rappi.com.mx',
    industry: 'Superapp / Delivery',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '4,000+',
    description: 'Superapp de delivery y servicios con RappiPay, RappiCredits y servicios financieros. Millones de usuarios y repartidores en CDMX con identidad verificada.',
    score: 81,
    scoreBreakdown: { industryFit: 22, companySize: 21, digitalMaturity: 23, securityNeeds: 15 },
    whyGoodFit: 'Millones de usuarios, repartidores y restaurantes necesitan identidad unificada. RappiPay requiere KYC/AML. Plataforma multi-tenant con alta seguridad transaccional.',
    suggestedSolution: 'Auth0 (CIAM multi-rol), Incode (verificación repartidores), Okta',
    contactApproach: 'Presentar solución de identidad para ecosistema multi-sided. ROI en reducción de fraude en RappiPay y aceleración de activación de repartidores.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/rappi',
    contacts: [
      { name: 'Sebastián García Hernández', title: 'Director de Seguridad', email: 's.garcia@rappi.com' },
      { name: 'Natalia López Martínez', title: 'VP de Ingeniería México', email: 'n.lopez@rappi.com' },
    ],
  },
  {
    id: 'S013',
    company: 'Inbursa (Grupo Carso)',
    website: 'https://www.inbursa.com',
    industry: 'Banca y Seguros',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '8,000+',
    description: 'Grupo financiero diversificado de Carlos Slim con banca, seguros, inversiones y pensiones. Aceleración digital con apertura de cuenta 100% en línea.',
    score: 79,
    scoreBreakdown: { industryFit: 24, companySize: 20, digitalMaturity: 18, securityNeeds: 17 },
    whyGoodFit: 'Cuenta digital requiere KYC y verificación biométrica. Regulación CNBV. Portafolio de productos financieros necesita identidad unificada cross-producto.',
    suggestedSolution: 'Auth0 (banca digital), Jumio (KYC apertura de cuenta), Okta Workforce',
    contactApproach: 'Presentar solución para apertura de cuenta 100% digital con verificación de identidad en menos de 5 minutos. Cumplimiento CNBV y LFPIORPI.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/grupo-financiero-inbursa',
    contacts: [
      { name: 'Roberto Silva Zamora', title: 'Director de TI', email: 'r.silva@inbursa.com.mx' },
      { name: 'Carmen Jiménez Robles', title: 'Directora de Ciberseguridad', email: 'c.jimenez@inbursa.com.mx' },
    ],
  },
  {
    id: 'S014',
    company: 'Walmart de México (Walmex)',
    website: 'https://www.walmartmexico.com',
    industry: 'Retail',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '220,000+',
    description: 'Mayor retailer de México y Centroamérica con 3,400+ tiendas. Inversión masiva en omnichannel, ecommerce y fidelización digital.',
    score: 79,
    scoreBreakdown: { industryFit: 20, companySize: 25, digitalMaturity: 18, securityNeeds: 16 },
    whyGoodFit: 'Base masiva de empleados y clientes digitales. Expansión de Walmart+ en México requiere CIAM. Supply chain digital con miles de proveedores necesita acceso federado.',
    suggestedSolution: 'Okta Workforce (empleados), Auth0 (loyalty/ecommerce), LeanIX',
    contactApproach: 'Enfocar en gestión de identidad para fuerza laboral masiva y onboarding de proveedores. ROI en reducción de helpdesk por reseteos de contraseña.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/walmart-de-mexico-y-centroamerica',
    contacts: [
      { name: 'Humberto Vázquez Torres', title: 'CIO', email: 'h.vazquez@walmart.com' },
      { name: 'Lucía Hernández Pérez', title: 'Directora de Ciberseguridad', email: 'l.hernandez@walmart.com' },
      { name: 'Marco Ruiz Garza', title: 'Director de Transformación Digital', email: 'm.ruiz@walmart.com' },
    ],
  },
  {
    id: 'S015',
    company: 'Hospital ABC',
    website: 'https://www.abchospital.com',
    industry: 'Salud',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '3,500+',
    description: 'Hospital privado de alta especialidad en CDMX, referente en atención de calidad internacional. Fuerte inversión en expediente clínico electrónico y portal de pacientes.',
    score: 74,
    scoreBreakdown: { industryFit: 20, companySize: 18, digitalMaturity: 19, securityNeeds: 17 },
    whyGoodFit: 'Portal de pacientes y expediente clínico digital requieren CIAM con cumplimiento NOM-024. Acceso seguro de médicos y personal clínico a sistemas sensibles necesita Zero Trust.',
    suggestedSolution: 'Auth0 (portal pacientes), Okta (personal médico), Yubico (MFA clínico)',
    contactApproach: 'Enfocar en cumplimiento NOM-024-SSA3 para sistemas de información hospitalaria y protección de datos de pacientes. Caso de uso: SSO para médicos en múltiples sistemas.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/hospital-abc',
    contacts: [
      { name: 'Fernando Morales García', title: 'Director de TI', email: 'f.morales@abchospital.com' },
      { name: 'Alejandra Castro López', title: 'Directora de Seguridad de Información', email: 'a.castro@abchospital.com' },
    ],
  },
  {
    id: 'S016',
    company: 'Telmex',
    website: 'https://www.telmex.com',
    industry: 'Telecomunicaciones',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '60,000+',
    description: 'Principal proveedor de telecomunicaciones en México del Grupo Carso. Millones de suscriptores de internet, telefonía y TV con portal self-service activo.',
    score: 72,
    scoreBreakdown: { industryFit: 18, companySize: 25, digitalMaturity: 16, securityNeeds: 13 },
    whyGoodFit: 'Millones de clientes en portal digital requieren CIAM. Empleados en toda la república con acceso a sistemas críticos necesitan IAM robusto. Infraestructura crítica nacional.',
    suggestedSolution: 'Okta Workforce, Auth0 (portal clientes), CrowdStrike (infraestructura crítica)',
    contactApproach: 'Abordar el reto de gestión de identidad para la inmensa base de clientes y empleados. ROI en reducción de llamadas a call center mediante self-service de identidad.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/telmex',
    contacts: [
      { name: 'Enrique Sánchez Martínez', title: 'CTO', email: 'e.sanchez@telmex.com' },
      { name: 'Rosa María Torres Ríos', title: 'Directora de Ciberseguridad', email: 'r.torres@telmex.com' },
    ],
  },
  {
    id: 'S017',
    company: 'AT&T México',
    website: 'https://www.att.com.mx',
    industry: 'Telecomunicaciones',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '15,000+',
    description: 'Operador de telecomunicaciones móviles con millones de suscriptores en México. Fuerte inversión en 5G y digitalización de servicios al cliente.',
    score: 71,
    scoreBreakdown: { industryFit: 18, companySize: 23, digitalMaturity: 17, securityNeeds: 13 },
    whyGoodFit: 'Millones de suscriptores en app y portal web requieren CIAM de alta disponibilidad. Empleados en operaciones de red necesitan Zero Trust. Expansión 5G crea nuevas necesidades de seguridad.',
    suggestedSolution: 'Auth0 (CIAM suscriptores), Zscaler (Zero Trust red), Okta (empleados)',
    contactApproach: 'Presentar solución CIAM escalable para alta concurrencia de usuarios móviles. Destacar Zero Trust para redes 5G y protección de infraestructura crítica.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/attmexico',
    contacts: [
      { name: 'Víctor Reyes Molina', title: 'Director de TI', email: 'v.reyes@att.com' },
      { name: 'Stephania Gómez Barrera', title: 'CISO', email: 's.gomez@att.com' },
    ],
  },
  {
    id: 'S018',
    company: 'Volaris',
    website: 'https://www.volaris.com',
    industry: 'Aerolíneas',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '7,000+',
    description: 'Aerolínea ultra low-cost con mayor participación de mercado en México. App móvil con millones de usuarios y fuerte presencia digital.',
    score: 69,
    scoreBreakdown: { industryFit: 18, companySize: 19, digitalMaturity: 18, securityNeeds: 14 },
    whyGoodFit: 'App con millones de pasajeros registrados necesita CIAM seguro y experiencia fluida. Digitalización de operaciones requiere acceso seguro para tripulaciones y personal de tierra.',
    suggestedSolution: 'Auth0 (CIAM app), Okta (empleados), Zscaler (Zero Trust operacional)',
    contactApproach: 'Presentar mejora en conversión de la app mediante login social y passwordless. Cumplimiento DGAC para sistemas de operaciones.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/volaris',
    contacts: [
      { name: 'Arturo Pérez Hernández', title: 'CIO', email: 'a.perez@volaris.com' },
      { name: 'Mónica Díaz Rodríguez', title: 'Directora de Tecnología', email: 'm.diaz@volaris.com' },
    ],
  },
  {
    id: 'S019',
    company: 'GNP Seguros',
    website: 'https://www.gnp.com.mx',
    industry: 'Seguros',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '12,000+',
    description: 'Aseguradora líder en México con seguros de vida, salud, autos y empresariales. Fuerte transformación digital con portal de autoservicio y app para asegurados.',
    score: 73,
    scoreBreakdown: { industryFit: 20, companySize: 22, digitalMaturity: 17, securityNeeds: 14 },
    whyGoodFit: 'Datos sensibles de asegurados requieren protección robusta. Portal digital con millones de usuarios necesita CIAM. Agentes independientes (miles) necesitan acceso federado seguro.',
    suggestedSolution: 'Auth0 (portal asegurados), Okta (agentes y empleados), Yubico',
    contactApproach: 'Enfocar en identidad federada para red de agentes independientes y cumplimiento CONDUSEF para protección de datos de asegurados.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/gnp-seguros',
    contacts: [
      { name: 'Luis Alberto González Ruiz', title: 'CIO', email: 'l.gonzalez@gnp.com.mx' },
      { name: 'Patricia Vargas Soto', title: 'Directora de Ciberseguridad', email: 'p.vargas@gnp.com.mx' },
    ],
  },
  {
    id: 'S020',
    company: 'DHL México',
    website: 'https://www.dhl.com/mx-es/home.html',
    industry: 'Logística',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '8,000+',
    description: 'Líder global en logística y mensajería con fuerte presencia en México. Plataforma digital de rastreo y gestión de envíos para miles de clientes empresariales.',
    score: 67,
    scoreBreakdown: { industryFit: 16, companySize: 20, digitalMaturity: 17, securityNeeds: 14 },
    whyGoodFit: 'Portal B2B con miles de clientes empresariales requiere CIAM multi-tenant. Empleados y mensajeros en campo necesitan acceso seguro a sistemas de rastreo.',
    suggestedSolution: 'Auth0 (portal B2B), Okta (workforce), Zscaler (Zero Trust operaciones)',
    contactApproach: 'Destacar experiencia en logística global. Presentar solución SSO para clientes corporativos y MFA para empleados en operaciones de alto riesgo.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/dhl',
    contacts: [
      { name: 'Christian Müller Sandoval', title: 'Director de TI México', email: 'c.muller@dhl.com' },
      { name: 'Verónica Ríos Castillo', title: 'Directora de Seguridad', email: 'v.rios@dhl.com' },
    ],
  },
  {
    id: 'S021',
    company: 'Grupo Bimbo',
    website: 'https://www.grupobimbo.com',
    industry: 'Manufactura / Alimentos',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '145,000+',
    description: 'Empresa panificadora más grande del mundo con presencia en 33 países. Fuerte inversión en transformación digital de supply chain y canales de distribución.',
    score: 74,
    scoreBreakdown: { industryFit: 18, companySize: 25, digitalMaturity: 17, securityNeeds: 14 },
    whyGoodFit: 'Fuerza laboral masiva dispersa globalmente requiere IAM unificado. Digitalización de rutas de distribución con miles de vendedores móviles necesita MFA robusto.',
    suggestedSolution: 'Okta (IAM workforce global), Yubico (MFA fábricas), LeanIX',
    contactApproach: 'Enfocarse en gestión de identidad para fuerza de ventas móvil y cumplimiento SOX para reportes financieros. Destacar integración con SAP.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/grupo-bimbo',
    contacts: [
      { name: 'Nicolás Garza López', title: 'CIO', email: 'n.garza@grupobimbo.com' },
      { name: 'Sofía Mendoza Reyes', title: 'Directora de Ciberseguridad', email: 's.mendoza@grupobimbo.com' },
      { name: 'Armando Castro Ibarra', title: 'Director de Transformación Digital', email: 'a.castro@grupobimbo.com' },
    ],
  },
  {
    id: 'S022',
    company: 'Accenture México',
    website: 'https://www.accenture.com/mx-es',
    industry: 'Consultoría TI',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '35,000+',
    description: 'Firma global de consultoría tecnológica con una de sus mayores operaciones en México. Especializada en transformación digital, cloud y ciberseguridad para grandes corporativos.',
    score: 66,
    scoreBreakdown: { industryFit: 18, companySize: 23, digitalMaturity: 16, securityNeeds: 9 },
    whyGoodFit: 'Empleados acceden a sistemas críticos de múltiples clientes. Zero Trust y PAM son prioridades. Como partner tecnológico, pueden convertirse en canal de reventa.',
    suggestedSolution: 'Okta Workforce, CrowdStrike (Zero Trust), Zscaler',
    contactApproach: 'Explorar alianza como canal/partner además de cliente directo. IAM para empleados en proyectos multi-cliente con acceso a ambientes seguros.',
    priority: 'Warm',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/accenture',
    contacts: [
      { name: 'Mauricio Torres García', title: 'Director de Ciberseguridad', email: 'm.torres@accenture.com' },
      { name: 'Daniela Morales Cruz', title: 'Lead Security Architect', email: 'd.morales@accenture.com' },
    ],
  },

  // ── COLD ─────────────────────────────────────────────────────────────────
  {
    id: 'S023',
    company: 'Liverpool (El Puerto de Liverpool)',
    website: 'https://www.liverpool.com.mx',
    industry: 'Retail',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '40,000+',
    description: 'Cadena de tiendas departamentales líder en México con fuerte presencia en ecommerce, programa de lealtad y servicios financieros (tarjeta de crédito propia).',
    score: 64,
    scoreBreakdown: { industryFit: 18, companySize: 22, digitalMaturity: 14, securityNeeds: 10 },
    whyGoodFit: 'Tarjeta de crédito Liverpool requiere KYC/AML. Millones de clientes en portal digital. Programa de lealtad con identidad unificada cross-canal.',
    suggestedSolution: 'Auth0 (CIAM loyalty), Jumio (KYC tarjeta), Okta Workforce',
    contactApproach: 'Enfocar en la integración del programa de lealtad y la tarjeta de crédito como punto de entrada. ROI en seguridad de fraude en ecommerce.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/liverpool-mexico',
    contacts: [
      { name: 'Alfonso Ramírez Vega', title: 'CIO', email: 'a.ramirez@liverpool.com.mx' },
      { name: 'Beatriz García Hernández', title: 'Directora de TI', email: 'b.garcia@liverpool.com.mx' },
    ],
  },
  {
    id: 'S024',
    company: 'TelevisaUnivision',
    website: 'https://www.televisaunivision.com',
    industry: 'Medios y Entretenimiento',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '15,000+',
    description: 'Mayor grupo de medios en español del mundo. Plataforma de streaming ViX con millones de suscriptores y contenido digital para audiencias hispanohablantes globales.',
    score: 63,
    scoreBreakdown: { industryFit: 16, companySize: 23, digitalMaturity: 15, securityNeeds: 9 },
    whyGoodFit: 'Plataforma de streaming ViX con millones de usuarios requiere CIAM. SSO entre canales digitales. Gestión de suscriptores de pago con autenticación robusta.',
    suggestedSolution: 'Auth0 (CIAM streaming), Okta (empleados), CrowdStrike',
    contactApproach: 'Presentar solución CIAM para reducir churn mediante login fluido y protección de cuentas. Caso de uso: SSO y gestión de identidad para plataforma ViX+.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/televisaunivision',
    contacts: [
      { name: 'Emmanuel López Sánchez', title: 'CTO', email: 'e.lopez@televisaunivision.com' },
      { name: 'Adriana Castro Fuentes', title: 'Directora de Seguridad Digital', email: 'a.castro@televisaunivision.com' },
    ],
  },
  {
    id: 'S025',
    company: 'Grupo Elektra',
    website: 'https://www.grupoelektra.com.mx',
    industry: 'Retail / Servicios Financieros',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '50,000+',
    description: 'Conglomerado de retail y servicios financieros con Banco Azteca. Millones de clientes de bajos ingresos con servicios de crédito y tiendas en todo México.',
    score: 61,
    scoreBreakdown: { industryFit: 18, companySize: 22, digitalMaturity: 12, securityNeeds: 9 },
    whyGoodFit: 'Banco Azteca tiene millones de clientes digitales con necesidades de KYC. Digitalización de crédito requiere verificación de identidad. Red de corresponsales necesita acceso seguro.',
    suggestedSolution: 'Jumio (KYC masivo), Auth0 (banca digital), Incode (biométrica)',
    contactApproach: 'Enfocar en digitalización de Banco Azteca y reducción de fraude en crédito de consumo. Verificación de identidad accesible para segmento C/D.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/grupo-elektra',
    contacts: [
      { name: 'Gerardo Muñoz Herrera', title: 'CIO', email: 'g.munoz@grupoelektra.com.mx' },
      { name: 'Silvia Domínguez Ortega', title: 'Directora de TI y Sistemas', email: 's.dominguez@grupoelektra.com.mx' },
    ],
  },
  {
    id: 'S026',
    company: 'MetLife México',
    website: 'https://www.metlife.com.mx',
    industry: 'Seguros',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '5,000+',
    description: 'Aseguradora global líder en seguros de vida y beneficios colectivos en México. Plataforma digital para agentes, empleados corporativos y asegurados.',
    score: 57,
    scoreBreakdown: { industryFit: 17, companySize: 19, digitalMaturity: 12, securityNeeds: 9 },
    whyGoodFit: 'Red de agentes con acceso a datos sensibles de clientes necesita MFA. Portal de asegurados requiere CIAM. Cumplimiento CONDUSEF para manejo de datos personales.',
    suggestedSolution: 'Okta (agentes y empleados), Auth0 (portal asegurados), Yubico',
    contactApproach: 'Presentar IAM para red de agentes distribuida con MFA y SSO. Cumplimiento de datos sensibles de salud y beneficiarios.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/metlife',
    contacts: [
      { name: 'Ricardo Soto González', title: 'CIO', email: 'r.soto@metlife.com.mx' },
      { name: 'Andrea Flores Jiménez', title: 'Directora de Seguridad de la Información', email: 'a.flores@metlife.com.mx' },
    ],
  },
  {
    id: 'S027',
    company: 'PEMEX',
    website: 'https://www.pemex.com',
    industry: 'Energía / Petróleo',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '110,000+',
    description: 'Empresa productiva del estado, principal productor de petróleo y gas de México. Infraestructura crítica nacional con operaciones en todo el territorio.',
    score: 59,
    scoreBreakdown: { industryFit: 15, companySize: 25, digitalMaturity: 10, securityNeeds: 9 },
    whyGoodFit: 'Infraestructura crítica nacional requiere Zero Trust y protección OT/IT. Massive workforce con acceso a sistemas críticos necesita IAM robusto. Cumplimiento normativo gubernamental.',
    suggestedSolution: 'CrowdStrike (OT/IT), Zscaler (Zero Trust), Okta (IAM workforce)',
    contactApproach: 'Abordar riesgo de ciberseguridad en infraestructura crítica. Destacar protección de sistemas SCADA y cumplimiento normativo para empresas productivas del estado.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/pemex',
    contacts: [
      { name: 'Héctor Ramírez Torres', title: 'CIO', email: 'h.ramirez@pemex.com' },
      { name: 'Martha Gutiérrez Reyes', title: 'Directora de Ciberseguridad', email: 'm.gutierrez@pemex.com' },
    ],
  },
  {
    id: 'S028',
    company: 'FIBRA Uno',
    website: 'https://www.fibrauno.mx',
    industry: 'Real Estate / FIBRA',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '500+',
    description: 'Principal FIBRA de México con más de 600 propiedades comerciales, industriales y de oficinas. Plataforma digital de gestión de inquilinos y operaciones.',
    score: 52,
    scoreBreakdown: { industryFit: 12, companySize: 17, digitalMaturity: 13, securityNeeds: 10 },
    whyGoodFit: 'Portal de inquilinos con datos financieros sensibles requiere CIAM. Acceso seguro a sistemas de gestión de propiedades. Empleados en múltiples propiedades necesitan SSO.',
    suggestedSolution: 'Auth0 (portal inquilinos), Okta (empleados), Yubico (MFA)',
    contactApproach: 'Presentar solución de portal de inquilinos seguro con SSO. Gestión de identidad para empleados en múltiples ubicaciones geográficas.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/fibra-uno',
    contacts: [
      { name: 'Gabriel Ortega Martínez', title: 'Director de TI', email: 'g.ortega@fibrauno.mx' },
      { name: 'Paola Hernández Cruz', title: 'Directora de Tecnología', email: 'p.hernandez@fibrauno.mx' },
    ],
  },
  {
    id: 'S029',
    company: 'Sears México',
    website: 'https://www.sears.com.mx',
    industry: 'Retail',
    size: 'Large',
    country: 'México',
    city: 'Ciudad de México',
    employees: '10,000+',
    description: 'Cadena de tiendas departamentales con Grupo Carso. Ecommerce en crecimiento y programa de tarjeta de crédito propia con transformación digital en curso.',
    score: 51,
    scoreBreakdown: { industryFit: 14, companySize: 18, digitalMaturity: 11, securityNeeds: 8 },
    whyGoodFit: 'Tarjeta de crédito requiere KYC. Portal de clientes con datos personales y financieros. Transformación digital en curso abre oportunidades de modernización de identidad.',
    suggestedSolution: 'Auth0 (ecommerce/CIAM), Jumio (KYC tarjeta), Okta',
    contactApproach: 'Abordar modernización de identidad como parte de transformación digital. ROI en reducción de fraude en ecommerce y tarjeta de crédito.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/sears-mexico',
    contacts: [
      { name: 'Eduardo Ríos García', title: 'Director de TI', email: 'e.rios@sears.com.mx' },
      { name: 'Miriam López Torres', title: 'Subdirectora de Sistemas', email: 'm.lopez@sears.com.mx' },
    ],
  },
  {
    id: 'S030',
    company: 'Sigma Alimentos',
    website: 'https://www.sigma-alimentos.com',
    industry: 'Manufactura / Alimentos',
    size: 'Enterprise',
    country: 'México',
    city: 'Ciudad de México',
    employees: '44,000+',
    description: 'Empresa multinacional de alimentos refrigerados del Grupo Alfa. Operaciones en 18 países con marcas como FUD, Bar-S y Braedt.',
    score: 56,
    scoreBreakdown: { industryFit: 16, companySize: 23, digitalMaturity: 10, securityNeeds: 7 },
    whyGoodFit: 'Operaciones globales requieren IAM unificado. Digitalización de cadena de suministro y distribución. Acceso seguro a sistemas ERP para empleados en múltiples países.',
    suggestedSolution: 'Okta (IAM global), Yubico (fábricas), LeanIX (arquitectura)',
    contactApproach: 'Presentar gestión de identidad para empleados multinacionales. Integración con SAP ERP y cumplimiento SOX para auditorías financieras.',
    priority: 'Cold',
    scrapedAt: '2026-03-05',
    linkedinUrl: 'https://www.linkedin.com/company/sigma-alimentos',
    contacts: [
      { name: 'Alejandro Garza Sánchez', title: 'CIO', email: 'a.garza@sigma-alimentos.com' },
      { name: 'Karla Morales Vega', title: 'Directora de Ciberseguridad', email: 'k.morales@sigma-alimentos.com' },
    ],
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────
export function getScoreLabel(score: number): string {
  if (score >= 85) return 'Excelente'
  if (score >= 70) return 'Alto'
  if (score >= 55) return 'Medio'
  return 'Bajo'
}

export function getScoreColor(score: number): { text: string; bg: string; border: string } {
  if (score >= 85) return { text: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-200' }
  if (score >= 70) return { text: 'text-[#0066cc]',   bg: 'bg-[#0066cc]/10', border: 'border-[#0066cc]/30' }
  if (score >= 55) return { text: 'text-amber-700',   bg: 'bg-amber-50',     border: 'border-amber-200'    }
  return              { text: 'text-[#94a3b8]',   bg: 'bg-[#f1f5f9]',    border: 'border-[#e2e8f0]'   }
}

export function getPriorityConfig(priority: Priority) {
  const map = {
    Hot:  { text: 'text-rose-700',  bg: 'bg-rose-50',  border: 'border-rose-200',  dot: 'bg-rose-500'  },
    Warm: { text: 'text-amber-700', bg: 'bg-amber-50', border: 'border-amber-200', dot: 'bg-amber-500' },
    Cold: { text: 'text-sky-700',   bg: 'bg-sky-50',   border: 'border-sky-200',   dot: 'bg-sky-500'   },
  }
  return map[priority]
}

export const industryOptions = [...new Set(seedLeads.map(l => l.industry))].sort()
export const priorityOptions: Priority[] = ['Hot', 'Warm', 'Cold']
export const LEAD_GOAL = 100
